USE [master]
GO

/****** Object:  Database [Shul]    Script Date: 1/8/2017 5:00:02 PM ******/
CREATE DATABASE [Shul]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shul', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Shul.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Shul_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Shul_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Shul] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shul].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shul] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shul] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shul] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shul] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shul] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shul] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Shul] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shul] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shul] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shul] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shul] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shul] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shul] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shul] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shul] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Shul] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shul] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shul] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shul] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shul] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shul] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shul] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shul] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Shul] SET  MULTI_USER 
GO

ALTER DATABASE [Shul] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shul] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shul] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shul] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Shul] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shul] SET  READ_WRITE 
GO

